"""MnTe: the Wannier model against GPAW, with and without SOC.

1. Spin up (Wannierised) and spin down (generated by the altermagnetic symmetry) against GPAW
   on the 24 NSCF k-points, and along a band path that is not part of the fit.
2. With SOC for n || y and n || c along the same path: the Wannier model (SOC to first order in the
   26-band subspace) against GPAW second-variation SOC with all 2 x 40 bands of the collinear run.
3. SCF k-grid: a 6x6x4-NSCF model built on a 9x9x6 SCF density (dft_scan.py) against the demo density (6x6x4).
4. Band crossings in the mirror plane k_x = 0, protected for n || a and gapped when n turns away from a.
5. The Wannier (NSCF) grid: interpolation error on the path for models built on 9x9x6 and 12x12x8.

Needs ../02_mnte/gpaw/{scf,nscf}.gpw and work/mnte-k9-nscf.gpw.
Optional, not needed for the talk. Run:  python mnte_validation.py   (about 15 min, one core)
"""
import io
import os
import warnings
from contextlib import redirect_stdout

import numpy as np
from gpaw import GPAW
from gpaw.spinorbit import soc_eigenstates

import wannierberri as wb
from mnte_checks import model

warnings.simplefilter("ignore")
energy = {"Energy": wb.calculators.tabulate.Energy(degen_thresh=1e-6)}
NSEMI = 8     # Mn 3s, 3p per spin: below the Wannier window
NVAL = 13     # valence bands per spin in the model

nscf = GPAW("../02_mnte/gpaw/nscf.gpw", txt=None, legacy_gpaw=True)
EF = nscf.get_fermi_level()
system, _ = model("../02_mnte/gpaw/nscf.gpw", "mnte-nscf6")    # the demo: 6x6x4 Wannier grid
c = system.real_lattice[2, 2]
kz = 0.35 * c / (2 * np.pi)


def segment(k0, k1, n):
    return [np.array(k0) + (np.array(k1) - np.array(k0)) * t for t in np.linspace(0, 1, n)]


# K-Gamma-K (kz = 0) | Mbar-Gammabar-Mbar (kz = 0.35 1/A) | Gamma-A
nodes = [([2 / 3, -1 / 3, 0], [0, 0, 0], 16), ([0, 0, 0], [-2 / 3, 1 / 3, 0], 16),
         ([-1 / 2, 0, kz], [0, 0, kz], 14), ([0, 0, kz], [1 / 2, 0, kz], 14), ([0, 0, 0], [0, 0, 1 / 2], 14)]
kpath = np.array([k for k0, k1, n in nodes for k in segment(k0, k1, n)])
B = system.recip_lattice
x = np.concatenate([[0], np.cumsum(np.linalg.norm(np.diff(kpath @ B, axis=0), axis=1))])
for i in np.cumsum([n for _, _, n in nodes])[:-1]:   # no distance across a jump between segments
    if not np.allclose(kpath[i - 1], kpath[i]):
        x[i:] -= x[i] - x[i - 1]

path_gpw = "work/mnte-path.gpw"
if not os.path.exists(path_gpw):
    GPAW("../02_mnte/gpaw/scf.gpw", txt=None, legacy_gpaw=True).fixed_density(kpts=kpath, symmetry="off", nbands=40,
                                                            txt=None).write(path_gpw)
calc = GPAW(path_gpw, txt=None, legacy_gpaw=True)


def wannier_bands(syst, k):
    with redirect_stdout(io.StringIO()):
        return wb.evaluate_k_path(syst, path=wb.Path(system, k_list=k), tabulators=energy,
                                  parallel=False).get_eigenvalues() - EF


def gpaw_bands(c_, spin, nk):
    return np.array([c_.get_eigenvalues(kpt=i, spin=spin) for i in range(nk)])[:, NSEMI:NSEMI + NVAL] - EF


lines = []
kibz = nscf.get_ibz_k_points()
for spin, name in [(0, "up (Wannierised)"), (1, "down (from symmetry)")]:
    syst = system.system_up if spin == 0 else system.system_down
    err_grid = np.abs(wannier_bands(syst, kibz) - gpaw_bands(nscf, spin, len(kibz))).max()
    Ew, Eg = wannier_bands(syst, kpath), gpaw_bands(calc, spin, len(kpath))
    err_path = np.abs(Ew - Eg)
    lines.append(f"no SOC, spin {name:22s} max error: {err_grid * 1e3:6.2f} meV on the 24 NSCF points, "
                 f"{err_path.max() * 1e3:6.1f} meV on the path (mean {err_path.mean() * 1e3:.1f})")
    if spin == 0:
        E_up = (Ew, Eg)
    else:
        E_dn = (Ew, Eg)

ends = np.cumsum([n for _, _, n in nodes])
ticks = [x[0], x[ends[0] - 1], x[ends[1] - 1], x[ends[2] - 1], x[ends[3] - 1], x[-1]]
labels = ["K", "Γ", "K|M̄", "Γ̄", "M̄|Γ", "A"]
results = {"x": x, "k": kpath, "ticks": ticks, "labels": labels, "EF": EF,
           "E_up_w": E_up[0], "E_up_g": E_up[1], "E_dn_w": E_dn[0], "E_dn_g": E_dn[1]}
iA = len(kpath) - 1
for label, (theta, phi) in {"y": (90, 90), "c": (0, 0)}.items():
    with redirect_stdout(io.StringIO()):
        system.set_soc_axis(theta=theta, phi=phi, units="degrees")
    Ew = wannier_bands(system, kpath)
    Eg = np.sort(soc_eigenstates(calc, theta=theta, phi=phi).eigenvalues(), axis=1)[:, 2 * NSEMI:2 * (NSEMI + NVAL)] - EF
    err = np.abs(Ew - Eg)
    top = Eg.max() - 1.0
    near = err[Eg > top]
    lines.append(f"SOC, n || {label}: max error {err.max() * 1e3:6.1f} meV over all 26 valence bands, "
                 f"{near.max() * 1e3:6.1f} meV within 1 eV of the top")
    shift_w = Ew[iA, -1] - E_up[0][iA, -1]
    shift_g = Eg[iA, -1] - E_up[1][iA, -1]
    lines.append(f"SOC, n || {label}: top level at A {Ew[iA, -1]:+.3f} (Wannier) {Eg[iA, -1]:+.3f} eV (GPAW); "
                 f"SOC shift {shift_w * 1e3:.0f} vs {shift_g * 1e3:.0f} meV")
    results.update({f"E_soc_{label}_w": Ew, f"E_soc_{label}_g": Eg})

# SCF k-grid: the 6x6x4-NSCF model on a 9x9x6 SCF density against the same model on the demo density
system6, _ = model("work/mnte-nscf6-nscf.gpw", "mnte-nscf6")
system9, _ = model("work/mnte-k9-nscf.gpw", "mnte-k9")
EF9 = GPAW("work/mnte-k9-nscf.gpw", txt=None, legacy_gpaw=True).get_fermi_level()
for label, (theta, phi, alpha) in {"off": (0, 0, 0), "n || y": (90, 90, 1), "n || c": (0, 0, 1)}.items():
    with redirect_stdout(io.StringIO()):
        for syst in (system6, system9):
            syst.set_soc_axis(theta=theta, phi=phi, units="degrees", alpha_soc=alpha)
    E6 = wannier_bands(system6, kpath)
    with redirect_stdout(io.StringIO()):
        E9 = wb.evaluate_k_path(system9, path=wb.Path(system9, k_list=kpath), tabulators=energy,
                                parallel=False).get_eigenvalues() - EF9
    # compare relative to the valence band top on the path, since E_F0 of the two runs differ
    d = np.abs((E9 - E9.max()) - (E6 - E6.max()))
    lines.append(f"SCF grid 9x9x6 vs 6x6x4, SOC {label}: max change {d.max() * 1e3:5.1f} meV "
                 f"(bands relative to the top on the path)")

# mirror-plane crossings: smallest splitting of each adjacent pair of the top 16 valence bands on k_x = 0
k2, k3 = np.meshgrid(np.linspace(0, 0.5, 41), np.linspace(0, 0.5, 41))
plane = np.stack([0 * k2.ravel(), k2.ravel(), k3.ravel()], axis=1)   # k_1 = 0 is the plane k_x = 0
gaps = {}
for phi in (0, 2.5):
    with redirect_stdout(io.StringIO()):
        system.set_soc_axis(theta=90, phi=phi, units="degrees", alpha_soc=1)
    E = wannier_bands(system, plane)[:, 2 * NVAL - 16:]
    gaps[phi] = np.diff(E, axis=1).min(axis=0)
closing = (gaps[0] < 1e-3) & (gaps[2.5] > 3e-3)
lines.append(f"k_x = 0 plane, 41x41 points: band pairs with a splitting < 1 meV for phi = 0 and > 3 meV for "
             f"phi = 2.5: {closing.sum()}; their smallest splittings "
             f"{np.round(gaps[0][closing] * 1e3, 2)} meV (phi = 0) and {np.round(gaps[2.5][closing] * 1e3, 1)} meV (phi = 2.5)")
results.update({"gaps_phi0": gaps[0], "gaps_phi2p5": gaps[2.5]})

# Wannier (NSCF) grid: interpolation error along the path, no SOC, and the SOC shift at A
for n in (9, 12):
    sys_n, _ = model(f"work/mnte-nscf{n}-nscf.gpw", f"mnte-nscf{n}")
    EF_n = GPAW(f"work/mnte-nscf{n}-nscf.gpw", txt=None, legacy_gpaw=True).get_fermi_level()
    with redirect_stdout(io.StringIO()):
        sys_n.set_soc_axis(alpha_soc=0)
        E_n = wb.evaluate_k_path(sys_n.system_up, path=wb.Path(sys_n, k_list=kpath), tabulators=energy,
                                 parallel=False).get_eigenvalues() - EF_n
    err = np.abs((E_n - E_n.max()) - (E_up[1] - E_up[1].max()))
    top = np.abs((E_n[:, -1] - E_n.max()) - (E_up[1][:, -1] - E_up[1].max()))
    shifts = []
    for theta, phi in [(0, 0), (90, 90)]:
        with redirect_stdout(io.StringIO()):
            sys_n.set_soc_axis(theta=theta, phi=phi, units="degrees", alpha_soc=1)
            E_A = wb.evaluate_k(sys_n, k=kpath[iA], calculators={"E": energy["Energy"]}).data[0]
        shifts.append((E_A.max() - EF_n - E_n[iA, -1]) * 1e3)
    lines.append(f"Wannier grid {n}x{n}x{2 * n // 3}: max error on the path {err.max() * 1e3:5.1f} meV (top band "
                 f"{top.max() * 1e3:4.1f} meV); SOC shift at A {shifts[0]:.0f} (n || c), {shifts[1]:.0f} meV (n || y)")
    results[f"E_up_nscf{n}"] = E_n

np.savez("results/mnte_validation.npz", **results)
open("results/mnte_validation.txt", "w").write("\n".join(lines) + "\n")
print("\n".join(lines))
